Hoca/Models/Ogrenci.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Hoca.Models
{
    public class Ogrenci
    {
        [Key]
        public int Id { get; set; }//ogrencinin numarasi key
        
        [NotMapped]
        public string EncryptedId { get; set; }

        [Required(ErrorMessage = "Adınızı girmeniz gerekmektedir")]
        [Display(Name ="Adı")]
        [MaxLength(30,ErrorMessage = "Adınız 30 karakterden uzun olamaz")]
        public string Ad { get; set; }
        //Soyad zorunlu degil
        [Display(Name = "Soyadı")]
        [MaxLength(30, ErrorMessage = "Soyadınız 30 karakterden uzun olamaz")]
        public string Soyad { get; set; }
        [Required(ErrorMessage = "Mail adresinizi girmeniz gerekmektedir")]
        [RegularExpression(@"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$",ErrorMessage ="Mailiniz yanlış")]
        [Display(Name = "Mail adresi")]
        [MaxLength(345, ErrorMessage = "Mail adresiniz 345 karakterden uzun olamaz")]
        public string Email { get; set; }//giris yaparken lazim
        [Required(ErrorMessage = "Şifrenizi girmeniz gerekmektedir")]
        [Display(Name = "Şifre")]
        [MinLength(6, ErrorMessage = "Şifreniz en az 6 karakter uzunluğunda olabilir")]
        public string Sifre { get; set; }//giris yaparken lazim
        [Required(ErrorMessage = "Lütfen bir sınıf seçin")]
        [Display(Name = "Sınıf")]
        public Siniflar? Sinif { get; set; }//kacinci sinif oldugu
        public IList<Sorular> SorduguSorular { get; set; }//ogrencinin sordugu sorular
        //public int sorulanSoruSayisi { get; set; } = 0;//ogrencinin bugune kadar sordugu soru sayisi
        public string FotoPath { get; set; }//ogrencinin fotografinin klasor yolu

    }
}

Hoca/Controllers/OgrenciController.cs
using Hoca.Models;
using Hoca.Security;
using Hoca.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Hosting;//IWebHostEnvironment
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Hoca.Controllers
{
    public class OgrenciController : Controller
    {
        private readonly IOgrenciRepository _ogrenciRepository;
        private readonly IWebHostEnvironment hostingEnvironment;
        private readonly ILogger<OgrenciController> _logger;
        private readonly IDataProtector protector;
        public OgrenciController(IOgrenciRepository ogrenciRepository,
                                IWebHostEnvironment hostingEnvironment,
                                ILogger<OgrenciController> logger,
                                IDataProtectionProvider dataProtectionProvider,
                                DataProtectionPurposeStrings dataProtectionPurposeStrings)
        {
            _ogrenciRepository = ogrenciRepository;
            this.hostingEnvironment = hostingEnvironment;
            _logger = logger;
            protector = dataProtectionProvider
                .CreateProtector(dataProtectionPurposeStrings.OgrenciIdRouteValue);
        }

        [AllowAnonymous]
        public ViewResult Index()
        {
            var model = _ogrenciRepository.GetAllOgrenci()
                        .Select(e =>
                        {
                            e.EncryptedId = protector.Protect(e.Id.ToString());
                            return e;
                        });
            return View(model);
        }

        public ViewResult Ogrenciler(string id)
        {
            //throw new Exception("Hata: Öğrenci gösteriminde hata oluştu.");

            int ogrenciId = Convert.ToInt32(protector.Unprotect(id));

            Ogrenci ogrenci = _ogrenciRepository.GetOgrenci(ogrenciId);
            if (ogrenci == null)
            {
                Response.StatusCode = 404;
                return View("OgrenciBulunamadi", ogrenciId);
            }
            HomeOgrencilerViewModel homeOgrencilerViewModel = new HomeOgrencilerViewModel()
            {
                Ogrenci = ogrenci,
                PageTitle = "Ogrenciler"
            };
            
            return View(homeOgrencilerViewModel);
        }

        [HttpGet]
        [Authorize]
        public ViewResult Olustur()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public ViewResult Duzenle(int id)
        {
            Ogrenci ogr = _ogrenciRepository.GetOgrenci(id);
            OgrenciDuzenleViewModel ogrenciDuzenleViewModel = new OgrenciDuzenleViewModel
            {
                Id = ogr.Id,
                Ad = ogr.Ad,
                Soyad = ogr.Soyad,
                Email = ogr.Email,
                Sifre = ogr.Sifre,
                Sinif = ogr.Sinif,
                FotoPath = ogr.FotoPath
            };
            return View(ogrenciDuzenleViewModel);
        }

        [HttpPost]
        [Authorize]
        public IActionResult Duzenle(OgrenciDuzenleViewModel model)
        {
            if (ModelState.IsValid)
            {
                Ogrenci ogrenci = _ogrenciRepository.GetOgrenci(model.Id);
                ogrenci.Ad = model.Ad;
                ogrenci.Soyad = model.Soyad;
                ogrenci.Email = model.Email;
                ogrenci.Sifre = model.Sifre;
                ogrenci.Sinif = model.Sinif;
                if (model.Foto != null) {
                    if(model.FotoPath != null)
                    {
                        string filePath = Path.Combine(hostingEnvironment.WebRootPath, 
                            "images", model.FotoPath);
                        System.IO.File.Delete(filePath);
                    }
                    ogrenci.FotoPath = FotoYukle(model);
                }

                _ogrenciRepository.Guncelle(ogrenci);
                return RedirectToAction("Index");
            }
            return View();
        }

        private string FotoYukle(OgrenciOlusturViewModel model)
        {
            string uniqFileName = null;
            if (model.Foto != null)
            {
                string yuklenenDosyalar = Path.Combine(hostingEnvironment.WebRootPath, "images");
                uniqFileName = Guid.NewGuid().ToString() + "_" + model.Foto.FileName;
                string dosyaYolu = Path.Combine(yuklenenDosyalar, uniqFileName);
                using(var fileStream = new FileStream(dosyaYolu, FileMode.Create))
                {
                    model.Foto.CopyTo(fileStream);
                }
            }

            return uniqFileName;
        }

        [HttpPost]
        [Authorize]
        public IActionResult Olustur(OgrenciOlusturViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqFileName = FotoYukle(model);

                Ogrenci newOgrenci = new Ogrenci
                {
                    Ad = model.Ad,
                    Soyad = model.Soyad,
                    Email = model.Email,
                    Sifre = model.Sifre,
                    Sinif = model.Sinif,
                    FotoPath = uniqFileName
                };
                _ogrenciRepository.Olustur(newOgrenci);
                return RedirectToAction("Ogrenciler", new { id = newOgrenci.Id });
            }
            return View();
        }

        /*[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }*/
    }
}

Hoca/Views/Ogrenci/Duzenle.cshtml
@model OgrenciDuzenleViewModel
@{
    ViewBag.Title = "Profilini Duzenle";
    var photoPath = "~/Images/" + (Model.FotoPath ?? "kisi.png");
}
<form enctype="multipart/form-data" asp-controller="Ogrenci" asp-action="Duzenle" method="post">
    <input hidden asp-for="Id" />
    <input hidden asp-for="FotoPath" />
    <div class="form-group row">
        <label asp-for="Ad" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Ad" class="form-control" placeholder="Ad" />
            <span asp-validation-for="Ad" class="text-danger"></span>
        </div>
        <label asp-for="Soyad" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Soyad" class="form-control" placeholder="Soyad" />
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Email" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Email" class="form-control" placeholder="Email" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <label asp-for="Sifre" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Sifre" class="form-control" placeholder="Sifre" />
            <span asp-validation-for="Sifre" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Sinif" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="Sinif" asp-items="Html.GetEnumSelectList<Siniflar>()">
                <option value="">Lütfen seçim yapın</option>
            </select>
            <span asp-validation-for="Sinif" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Foto" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="custom-file">
                <!--multiple--><input asp-for="Foto" class="form-control custom-file-input" />
                <label class="custom-file-label">Fotoğrafı Değiştir</label>
            </div>
        </div>
    </div>
    <!--<div class="form-group row col-sm-4 offset-4">-->
        <img src="@photoPath" class="imageDuzenleme" asp-append-version="true" />
    <!--</div>-->
    
    <div asp-validation-summary="All"></div>
    
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Güncelle</button>
            <a asp-controller="Ogrenci" asp-action="Index" class="btn btn-primary">Vazgeç</a>
        </div>
    </div>
    @section Scripts {
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
        </script>
    }
</form>

Hoca/Views/Ogrenci/Index.cshtml
@model IEnumerable<Ogrenci>
@{
    ViewBag.Title = "Ogrenci Listesi";
}
<div class="card-deck">
    @foreach(var ogr in Model)
    {
        var photoPath = "~/Images/" + (ogr.FotoPath ?? "kisi.png");
        <div class="col-sm-3" style="min-width: 18rem; max-width: 30.5%;">
            <div class="card-footer text-center">
                <p>Ad: @ogr.Ad</p>
                <p>Mail: @ogr.Email</p>
                <p>Sınıf: @ogr.Sinif</p>
            </div>
            <img class="card-img-top imageDuzenleme" src="@photoPath" asp-append-version="true"/>
            <a asp-controller="Ogrenci" asp-action="Ogrenciler" 
               asp-route-id="@ogr.EncryptedId" class="btn btn-primary m-1">Detay</a>
            <a asp-controller="Ogrenci" asp-action="Duzenle" 
               asp-route-id="@ogr.Id" class="btn btn-primary m-1">Düzenle</a>
        </div>
    }
</div>

Hoca/Views/Ogrenci/OgrenciBulunamadi.cshtml
@model int

@{ 
    ViewBag.Title = "404 Hatası";
} 

<div class="alert alert-danger mt-1 mb-1">
    <h4>404 Sayfa Bulunamadı Hatası:</h4>
    <hr />
    <h5>@Model numaralı öğrencinin sayfası bulunamadı.</h5>
</div>

<a asp-action="Index" asp-controller="Ogrenci" class="btn btn-outline-success">
    Ana sayfaya dönmek için tıklayınız.
</a>

Hoca/Views/Ogrenci/Ogrenciler.cshtml
@model HomeOgrencilerViewModel
@{
    ViewBag.Title = "Öğrencinin Kendi Sayfası";
    var photoPath = "~/Images/" + (Model.Ogrenci.FotoPath ?? "kisi.png");
}

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title></title>
</head>
<body>
    <h3>@Model.PageTitle</h3>

    <div>
        Ad: @Model.Ogrenci.Ad
    </div>
    <div>
        Soyad: @Model.Ogrenci.Soyad
    </div>
    <div>
        Mail: @Model.Ogrenci.Email
    </div>
    <div>
        Sınıf: @Model.Ogrenci.Sinif
    </div>
    <img class="card-img-top imageDuzenleme" src="@photoPath" asp-append-version="true" />
    <a asp-controller="Ogrenci" asp-action="Duzenle" asp-route-id="@Model.Ogrenci.Id" 
       class="btn btn-primary m-1">Profili Düzenle</a>
    @section Scripts {
        <script src="~/js/site.js"></script>
    }
</body>
</html>

Hoca/Views/Ogrenci/Olustur.cshtml
@model OgrenciOlusturViewModel
@{ 
    ViewBag.Title = "Ogrenci Olustur";
}
<form enctype="multipart/form-data" asp-controller="Ogrenci" asp-action="Olustur" method="post">
    <div class="form-group row">
        <label asp-for="Ad" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Ad" class="form-control" placeholder="Ad" />
            <span asp-validation-for="Ad" class="text-danger"></span>
        </div>
        <label asp-for="Soyad" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Soyad" class="form-control" placeholder="Soyad" />
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Email" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Email" class="form-control" placeholder="Email" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <label asp-for="Sifre" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Sifre" class="form-control" placeholder="Sifre" type="password" />
            <span asp-validation-for="Sifre" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Sinif" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="Sinif" asp-items="Html.GetEnumSelectList<Siniflar>()">
                <option value="">Lütfen seçim yapın</option>
            </select>
            <span asp-validation-for="Sinif" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Foto" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <div class="custom-file">
                <!--multiple--><input asp-for="Foto" class="form-control custom-file-input" />
                <label class="custom-file-label">Fotoğraf Seç</label>
            </div>
        </div>
    </div>
    <div asp-validation-summary="All"></div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit">Oluştur</button>
        </div>
    </div>
    @section Scripts {
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
        </script>
    } 
</form>