Hoca/Controllers/AdministrationController.cs
using Hoca.Models;
using Hoca.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Hoca.Controllers
{
    [Authorize(Policy = "AdminRolePolicy")]
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<OgrenciUser> userManager;
        private readonly ILogger<AdministrationController> logger;

        public AdministrationController(RoleManager<IdentityRole> roleManager,
                                        UserManager<OgrenciUser> userManager,
                                        ILogger<AdministrationController> logger)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            this.logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> YonetKullaniciClaims(string userId)
        {
            var user = await userManager.FindByIdAsync(userId);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"{userId} id'li kullanıcı bulunamadı.";
                return View("SayfaBulunamadi");
            }

            var existingUserClaims = await userManager.GetClaimsAsync(user);

            var model = new UserClaimsViewModel
            {
                UserId = userId
            };

            foreach (Claim claim in ClaimsStore.AllClaims)
            {
                UserClaim userClaim = new UserClaim
                {
                    ClaimType = claim.Type
                };

                if (existingUserClaims.Any(c => c.Type == claim.Type && c.Value == "true"))
                {
                    userClaim.IsSelected = true;
                }

                model.Cliams.Add(userClaim);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> YonetKullaniciClaims(UserClaimsViewModel model)
        {
            var user = await userManager.FindByIdAsync(model.UserId);

            if(user == null)
            {
                ViewBag.ErrorMessage = $"{model.UserId} id'li kullanıcı bulunamadı.";
                return View("SayfaBulunamadi");
            }

            var claims = await userManager.GetClaimsAsync(user);
            var result = await userManager.RemoveClaimsAsync(user, claims);

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Claim silinemedi.");
                return View(model);
            }

            result = await userManager.AddClaimsAsync(user,
                model.Cliams.Select(c => new Claim(c.ClaimType, c.IsSelected ? "true" : "false")));
            
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Claim eklenmek için seçilmedi.");
                return View(model);
            }

            return RedirectToAction("DuzenleKullanici", new { Id = model.UserId});
        }


        [HttpGet]
        public async Task<IActionResult> KullaniciRolDuzenle(string userId)
        {
            ViewBag.userId = userId;

            var user = await userManager.FindByIdAsync(userId);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"{userId} id'li kişi bulunamadı.";
                return View("SayfaBulunamadi");
            }

            var model = new List<UserRolesViewModel>();
            
            foreach (var role in roleManager.Roles)
            {
                var userRolesViewModel = new UserRolesViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };

                if(await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.IsSelected = true;
                }
                else
                {
                    userRolesViewModel.IsSelected = false;
                }

                model.Add(userRolesViewModel);
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> KullaniciRolDuzenle(List<UserRolesViewModel> model ,string userId)
        {
            var user = await userManager.FindByIdAsync(userId);

            if(user == null)
            {
                ViewBag.ErrorMessage = $"{userId} id'li kullanıcı bulunamadı";
                return View("SayfaBulunamadi");
            }

            var roles = await userManager.GetRolesAsync(user);
            var result = await userManager.RemoveFromRolesAsync(user, roles);

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Kullanıcı belirtilen rolden silinemedi.");
                return View(model);
            }

            result = await userManager.AddToRolesAsync(user, 
                model.Where(x => x.IsSelected).Select(y => y.RoleName));
            
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Eklemek için rol seçilmedi.");
                return View(model);
            }
            return RedirectToAction("DuzenleKullanici", new { Id = userId });
        }

        [HttpPost]
        public async Task<IActionResult> SilKullanici(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"{id} id numaralı kişi bulunamadı.";
                return View("SayfaBulunamadi");
            }
            else
            {
                var result = await userManager.DeleteAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("KullanicilariListele");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View("KullanicilariListele");
            }
        }

        [HttpPost]
        [Authorize(Policy = "RolSilPolicy")]
        public async Task<IActionResult> SilRol(string id)
        {
            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"{id} id numaralı rol bulunamadı.";
                return View("SayfaBulunamadi");
            }
            else
            {
                try
                {
                    var result = await roleManager.DeleteAsync(role);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("ListRoles");
                    }

                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }

                    return View("ListRoles");
                }
                catch (DbUpdateException ex)
                {
                    logger.LogError($"Rol silerken hata oldu {ex}");

                    ViewBag.ErrorTitle = $"{role.Name} rolü kullanımda.";
                    ViewBag.Error = $"{role.Name} rolüne sahip kullanıcılar bulunmakta"
                        + $". Önce kullanıcıları silin."
                        + $" Ardından rolü silmeyi tekrar deneyin.";
                    return View("SayfaBulunamadi");
                }
            }
        }

        [HttpGet]
        public IActionResult KullanicilariListele()
        {
            var kullanicilar = userManager.Users;
            return View(kullanicilar);
        }

        [HttpGet]
        public async Task<IActionResult> DuzenleKullanici(string id)
        {
            var user = await userManager.FindByIdAsync(id);

            if(user == null)
            {
                ViewBag.ErrorMessage = $"{id} id'li kullanıcı bulunamadı.";
                return View("SayfaBulunamadi");
            }

            var userClaims = await userManager.GetClaimsAsync(user);
            var userRoles = await userManager.GetRolesAsync(user);

            var model = new EditUserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                UserName = user.UserName,
                Class = user.Sinif,
                Claims = userClaims.Select(c => c.Type + " : " + c.Value).ToList(),
                Roles = userRoles
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> DuzenleKullanici(EditUserViewModel model)
        {
            var user = await userManager.FindByIdAsync(model.Id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"{model.Id} id'li kullanıcı bulunamadı.";
                return View("SayfaBulunamadi");
            }
            else
            {
                user.UserName = model.UserName;
                user.Email = model.Email;
                user.Sinif = model.Class;

                var sonuc = await userManager.UpdateAsync(user);

                if (sonuc.Succeeded)
                {
                    return RedirectToAction("KullanicilariListele");
                }

                foreach (var error in sonuc.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View(model);
            }

        }

        [HttpGet]
        public IActionResult RolOlustur()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> RolOlustur(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {

Hoca/Views/Administration/AccessDenied.cshtml
<div class="text-center">
    <h1 class="text-danger">Erişim Engellendi</h1>
    <h5 class="text-danger">Bu sayfaya erişim izniniz bulunmamaktadır.</h5>
    <img src="~/images/tenor.gif" />
</div>

Hoca/Views/Administration/DuzenleKullanici.cshtml
@model EditUserViewModel

@{ 
    ViewBag.Title = "Kullanıcı Düzenle";
} 

<h2>Kullanıcıyı Düzenle</h2>

<form method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Id" disabled class="form-control" />
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Email" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="UserName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="UserName" class="form-control" />
            <span asp-validation-for="UserName" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="Class" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="Class" asp-items="Html.GetEnumSelectList<Siniflar>()">
            </select>
            <span asp-validation-for="Class" class="text-danger"></span>
        </div>
    </div>

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Güncelle</button>
            <a asp-action="KullanicilariListele" class="btn btn-primary">İptal</a>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h3>Kullanıcının Rolleri</h3>
        </div>
        <div class="card-body">
            @if (Model.Roles.Any())
            {
                foreach(var role in Model.Roles)
                {
                    <h5 class="card-title">@role</h5>
                }
            }
            else
            {
                <h5 class="card-title">Rolü bulunmamakta.</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-action="KullaniciRolDuzenle" asp-route-userId="@Model.Id" class="btn btn-primary">Rolü Düzenle</a>
        </div>
    </div>

    <div class="card mt-3">
        <div class="card-header">
            <h3>Kullanıcı Claims</h3>
        </div>
        <div class="card-body">
            @if (Model.Claims.Any())
            {
                foreach (var claim in Model.Claims)
                {
                    <h5 class="card-title">@claim</h5>
                }
            }
            else
            {
                <h5 class="card-title">Şu an için yok.</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-action="YonetKullaniciClaims" asp-route-userId="@Model.Id"
               class="btn btn-primary">
                Claims Yönet
            </a>
        </div>
    </div>
</form>

Hoca/Views/Administration/KullaniciDuzenle.cshtml
@model List<UserRoleViewModel>

@{ 
    var roleId = ViewBag.roleId;
}

<form method="post">
    <div class="card">
        <div class="card-header">
            <h3>Kullanıcı ekle veya sil</h3>
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model[i].UserId"/>
                    <input type="hidden" asp-for="@Model[i].UserEmail"/>
                    <input asp-for="@Model[i].IsSelected" class="form-check-input"/>
                    <label class="form-check-label" asp-for="@Model[i].IsSelected">@Model[i].UserEmail</label>
                    <label class="form-check-label">@Model[i].UserId</label>
                </div>
            }
        </div>
        <div class="card-footer">
            <input type="submit" value="Update" class="btn btn-primary"/>
            <a asp-action="RolDuzenle" asp-route-id="@roleId" class="btn btn-primary">İptal</a>
        </div>
    </div>
</form>

Hoca/Views/Administration/KullaniciRolDuzenle.cshtml
@model List<UserRolesViewModel>

@{ 
    var userId = ViewBag.userId;
}

<form method="post">
    <div class="card">
        <div class="card-header">
            <h3>Kullanıcının Rolünü Düzenle</h3>
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model[i].RoleId"/>
                    <input type="hidden" asp-for="@Model[i].RoleName"/>
                    <input asp-for="@Model[i].IsSelected" class="form-check-input"/>
                    <label class="form-check-label" asp-for="@Model[i].IsSelected ">
                    @Model[i].RoleName</label>
                </div>
            }

            <div asp-validation-summary="All" class="text-danger"></div>

        </div>
        <div class="card-footer">
            <input type="submit" value="Update" class="btn btn-primary" />
            <a asp-action="DuzenleKullanici" asp-route-id="@userId" 
               class="btn btn-primary">İptal</a>
        </div>
    </div>
</form>

Hoca/Views/Administration/KullanicilariListele.cshtml
@model IEnumerable<OgrenciUser>

@{
    ViewBag.Title = "Kullanıcılar";
}

<h1>Tüm Kullanıcılar</h1>

@if (Model.Any())
{
    <a asp-action="KayitOl" asp-controller="Hesap" class="btn btn-primary mb-2">Kullanıcı Ekle</a>


    foreach (var user in Model)
    {
        <div class="card mb-3">
            <div class="card-header">
                Kullanıcı id: @user.Id
            </div>
            <div class="card-body">
                <h5 class="card-title">@user.UserName</h5>
                <h5 class="card-title">@user.Email</h5>
            </div>
            <div class="card-footer">
                <form asp-action="SilKullanici" asp-route-id="@user.Id" method="post">
                    <a asp-action="DuzenleKullanici" asp-controller="Administration"
                       asp-route-id="@user.Id" class="btn btn-primary">Düzenle</a>
                    <span id="confirmDeleteSpan_@user.Id" style="display:none">
                        <span>Silmek istediğine emin misin?</span>
                        <button type="submit" class="btn btn-danger">Evet</button>
                        <a href="#" class="btn btn-primary"
                           onclick="confirmDelete('@user.Id', false)">Hayır</a>
                    </span>

                    <span id="deleteSpan_@user.Id">
                        <a href="#" class="btn btn-primary"
                           onclick="confirmDelete('@user.Id', true)">Sil</a>
                    </span>
                </form>
            </div>
        </div>
    }
}
else
{
    <div class="card">
        <div class="card-header">
            Veri tabanında kullanıcı bulunmamaktadır.
        </div>
        <div class="card-body">
            <h5 class="card-title">El ile kullanıcı oluşturmak için butona basın.</h5>
            <a class="btn btn-primary" asp-controller="Hesap" asp-action="KayitOl"></a>
        </div>
    </div>
}

@section Scripts{
    <script src="~/js/site.js"></script>
}

Hoca/Views/Administration/ListRoles.cshtml
@model IEnumerable<IdentityRole>

@using Microsoft.AspNetCore.Authorization

@inject IAuthorizationService authorizationService

@{
    ViewBag.Title = "Tüm Roller";
}

<h2>Tüm Roller</h2>

@if (Model.Any())
{
    <a class="btn btn-primary"
       asp-action="RolOlustur" asp-controller="Administration">Rol Oluştur</a>
    foreach (var role in Model)
    {
        <div class="card mb-3">
            <div class="card-header">
                Rol id: @role.Id
            </div>
            <div class="card-body">
                <h5 class="card-title">@role.Name</h5>
            </div>
            <div class="card-footer">
                <form asp-action="SilRol" asp-route-id="@role.Id" method="post">
                    @if ((await authorizationService.AuthorizeAsync(User, "RolDuzenlePolicy")).Succeeded)
                    {
                        <a asp-action="RolDuzenle" asp-controller="Administration"
                           asp-route-id="@role.Id" class="btn btn-primary">Düzenle</a>
                    }
                    <span id="confirmDeleteSpan_@role.Id" style="display:none">
                        <span>Silmek istediğine emin misin?</span>
                        <button type="submit" class="btn btn-danger">Evet</button>
                        <a href="#" class="btn btn-primary"
                           onclick="confirmDelete('@role.Id', false)">Hayır</a>
                    </span>

                    <span id="deleteSpan_@role.Id">
                        <a href="#" class="btn btn-primary"
                           onclick="confirmDelete('@role.Id', true)">Sil</a>
                    </span>
                </form>
            </div>
        </div>
    }
}
else
{
    <div class="card">
        <div class="card-header">
            Rol Oluştur
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Butonu kullanarak rol oluşturabilirsin.
            </h5>
            <a class="btn btn-primary"
               asp-action="RolOlustur" asp-controller="Administration">Rol Oluştur</a>
        </div>
    </div>
}

@section Scripts{ 
    <script src="~/js/site.js"></script>
}

Hoca/Views/Administration/RolDuzenle.cshtml
@model EditRoleViewModel

@{
    ViewBag.Title = "Rolü Düzenle";
}

<h2>Rolü Düzenle</h2>

<form method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="Id" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="Id" disabled class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="RoleName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="RoleName" class="form-control">
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
    </div>

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Güncelle</button>
            <a asp-action="ListRoles" class="btn btn-primary">İptal Et</a>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h3>Kayıtlılar</h3>
        </div>
        <div class="card-body">
            @if(Model.Users.Any())
            {
                foreach(var user in Model.Users)
                {
                    <h5 class="card-title">@user</h5>
                }
            }
            else
            {
                <h5 class="card-title">Bu rolde kullanıcı yok.</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-action="KullaniciDuzenle" asp-controller="Administration" 
               asp-route-roleId="@Model.Id" class="btn btn-primary">Kullanıcı Ekle veya Sil</a>
        </div>
    </div>

</form>

Hoca/Views/Administration/RolOlustur.cshtml
@model CreateRoleViewModel

@{
    ViewBag.Title = "Yeni Rol Ekle";
}

<h2>Rol Ekle</h2>

<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RoleName"></label>
                <input asp-for="RoleName" class="form-control" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>

            <button type="submit" class="btn btn-primary">Rol Ekle</button>
        </form>
    </div>
</div>

Hoca/Views/Administration/YonetKullaniciClaims.cshtml
@model UserClaimsViewModel

<form method="post">
    <div class="card">
        <div class="card-header">
            <h3>Kullanıcı Claims Yönetimi</h3>
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Cliams.Count; i++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model.Cliams[i].ClaimType" />
                    <input asp-for="@Model.Cliams[i].IsSelected" class="form-check-input" />
                    <label class="form-check-label" asp-for="@Model.Cliams[i].IsSelected">
                        @Model.Cliams[i].ClaimType
                    </label>
                </div>
            }
            <div asp-validation-summary="All" class="text-danger"></div>
        </div>
        <div class="card-footer">
            <input type="submit" value="Update" class="btn btn-primary" />
            <a asp-action="DuzenleKullanici" asp-route-id="@Model.UserId" 
               class="btn btn-primary">İptal
            </a>
        </div>
    </div>

</form>